using Asp.NetCoreWebApi1.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Asp.NetCoreWebApi1.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CategoryController : ControllerBase
    {
        public static List<Category> category = new List<Category>()
        {
            new Category() {Id=107131, CategoryName= "2 pcs set", UnitName="Pcs", Name= "2 Pcs Set", Code= "SSS00026", ParentCode="null", ProductBarcode="SSS00026", Description="", BrandName="", SizeName="2Y to 8Y", ColorName="one color 2 style", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=01/02/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107127, CategoryName= "2 pre owned iphone", UnitName="Pcs", Name= "iphone 11", Code= "100066", ParentCode="null", ProductBarcode="100066", Description="", BrandName="Apple", SizeName="64GB", ColorName="", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="Nurul Absar", TotalSales=1, LastSalesDate=04/03/23, LastSalesCustomer="Walk in Customer", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107118, CategoryName= "UNOFFICIAL", UnitName="Pcs", Name= "S21 ULTRA", Code= "100290", ParentCode="null", ProductBarcode="100290", Description="", BrandName="Samsung", SizeName="12/256", ColorName="SILVER", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="Cash Supplier", TotalSales=1, LastSalesDate=04/03/23, LastSalesCustomer="walk in customer", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107117, CategoryName= "Boys t shirt", UnitName="Pcs", Name= "T SHIRT", Code= "SSS00025", ParentCode="null", ProductBarcode="SSS00025", Description="", BrandName="", SizeName="2Y to 7Y", ColorName="one color", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=5, LastPurchaseDate=04/03/23, LastPurchaseSupplier="ctg wearhouse", TotalSales=0, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107116, CategoryName= "Boys Ramper", UnitName="Pcs", Name= "ramper", Code= "SSS00024", ParentCode="null", ProductBarcode="SSS00024", Description="", BrandName="", SizeName="6m to 24m", ColorName="one color", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=0, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107115, CategoryName= "Girls frock", UnitName="Pcs", Name= "Frock", Code= "SSS00023", ParentCode="null", ProductBarcode="SSS00023", Description="", BrandName="", SizeName="6m to 7Y", ColorName="one color", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=22, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=0, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107114, CategoryName= "Girls frock", UnitName="Pcs", Name= "Frock", Code= "SSS00022", ParentCode="null", ProductBarcode="SSS00022", Description="", BrandName="", SizeName="2Y to 7Y", ColorName="one color", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107113, CategoryName= "Camping Pillow", UnitName="Pcs", Name= "Travel Pillow", Code= "100275", ParentCode="null", ProductBarcode="100275", Description="2", BrandName="", SizeName="", ColorName="", ModelName="null", VariantName="null", OldPrice=0, Price=1550, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107112, CategoryName= "Unofficial", UnitName="Pcs", Name= "3310", Code= "100289", ParentCode="null", ProductBarcode="100289", Description="", BrandName="NOKIA", SizeName="", ColorName="Blue", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107111, CategoryName= "Unofficial", UnitName="Pcs", Name= "14 PRO", Code= "100288", ParentCode="null", ProductBarcode="100288", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107110, CategoryName= "Mobile - Intact", UnitName="Pcs", Name= "Redmi 10C", Code= "100288", ParentCode="null", ProductBarcode="100288", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107109, CategoryName= "Mobile-Used", UnitName="Pcs", Name= "POCO M2 PRO", Code= "100288", ParentCode="null", ProductBarcode="100288", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107108, CategoryName= "Mens", UnitName="Pcs", Name= "DENIM PANT levies", Code= "100101", ParentCode="null", ProductBarcode="100101", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107107, CategoryName= "Bag", UnitName="Pcs", Name= "White Organizer bag", Code= "B1071", ParentCode="null", ProductBarcode="B1071", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="White", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107106, CategoryName= "Bag", UnitName="Pcs", Name= "unicorn organizer bag", Code= "B1070", ParentCode="null", ProductBarcode="B1070", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PINK", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107105, CategoryName= "Sharee", UnitName="Pcs", Name= "sunflower sharee", Code= "S100288", ParentCode="null", ProductBarcode="S100288", Description="", BrandName="", SizeName="", ColorName="White", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107104, CategoryName= "Bag", UnitName="Pcs", Name= "Purple Organizer bag", Code= "B1068", ParentCode="null", ProductBarcode="B1068", Description="", BrandName="", SizeName="", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107103, CategoryName= "Bag", UnitName="Pcs", Name= "cat organizer bag", Code= "B1069", ParentCode="null", ProductBarcode="B1069", Description="", BrandName="", SizeName="", ColorName="Peach", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107102, CategoryName= "Mobile", UnitName="Pcs", Name= "Redmi Note 12 Pro", Code= "100288", ParentCode="null", ProductBarcode="100288", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107101, CategoryName= "Girls Tops", UnitName="Pcs", Name= "Girls Top NewBorn", Code= "211023", ParentCode="null", ProductBarcode="211023", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107100, CategoryName= "Unofficial", UnitName="Pcs", Name= "XS MAX", Code= "100287", ParentCode="null", ProductBarcode="100287", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107099, CategoryName= "LCD DISPLAY", UnitName="Pcs", Name= "Oppo A54 LCD", Code= "100311", ParentCode="null", ProductBarcode="100311", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107098, CategoryName= "LCD DISPLAY", UnitName="Pcs", Name= "OPPO A31 LCD", Code= "100310", ParentCode="null", ProductBarcode="100310", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107097, CategoryName= "LCD DISPLAY", UnitName="Pcs", Name= "Redmi Note 11 INSELL LCD", Code= "100309", ParentCode="null", ProductBarcode="100309", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107096, CategoryName= "Pre Owned Android", UnitName="Pcs", Name= "Samsung S22+", Code= "100065", ParentCode="null", ProductBarcode="100065", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107095, CategoryName= "Unofficial Mobile", UnitName="Pcs", Name= "IPhone 14", Code= "100064", ParentCode="null", ProductBarcode="100064", Description="", BrandName="I PHONE", SizeName="128GB", ColorName="PURPEL", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107094, CategoryName= "Polish 2", UnitName="Pcs", Name= "Soft 99 White", Code= "Polish 2", ParentCode="null", ProductBarcode="Polish 2", Description="", BrandName="Artex", SizeName="", ColorName="", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107093, CategoryName= "Polish", UnitName="Pcs", Name= "Soft 99 Red", Code= "Polish 5", ParentCode="null", ProductBarcode="Polish 5", Description="", BrandName="Artex", SizeName="", ColorName="", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107092, CategoryName= "Polish", UnitName="Pcs", Name= "Soft 99 Blue", Code= "Polish 4", ParentCode="null", ProductBarcode="Polish 4", Description="", BrandName="Artex", SizeName="", ColorName="", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
            new Category() {Id=107091, CategoryName= "Polish", UnitName="Pcs", Name= "Soft 99 Black", Code= "Polish 3", ParentCode="null", ProductBarcode="Polish 3", Description="", BrandName="Artex", SizeName="", ColorName="", ModelName="null", VariantName="null", OldPrice=0, Price=0, CostPrice=0, WarehouseList="[]", stock= 0, TotalPurchase=0, LastPurchaseDate=04/03/23, LastPurchaseSupplier="null", TotalSales=24, LastSalesDate=04/03/23, LastSalesCustomer="Khalid Bhai", ImagePath="null", Type="simple", Status="publish" },
        };
        [HttpGet]
        public List<Category> Get()
        {
            return category;
        }
        [HttpPost]
        public IActionResult Post([FromBody] Category cat)
        {
            category.Add(cat);
            return Ok(category);
        }
    }
}
